"""Ontology-Based Shape Entailer

This module extends SHACL shapes based on ontology relationships (TBox),
without using the data graph (ABox). It adds new property shapes to closed
shapes based on rdfs:subPropertyOf and owl:equivalentProperty relationships.
"""

import logging
from rdflib import Graph, URIRef, BNode, Literal, Namespace
from rdflib.namespace import OWL, RDF, RDFS, SH
from typing import Set, Tuple, Dict
from pre_shacl.EntailEngine import InferenceLevel
from pre_shacl.rdf_list_utils import get_elements_in_rdf_list
from pre_shacl.shape_analyzer import get_all_target_classes_for_shape
from pre_shacl.ontology_closure import compute_subproperty_closure

logger = logging.getLogger(__name__)

# Namespace for marking generated nodes
EX = Namespace("http://example.org/generated#")


def mark_generated_node(shacl_graph: Graph, node: BNode) -> None:
    """
    Mark a property shape as generated by ontology entailer.
    
    Adds: node ex:generatedBy "ontology_entailer" .
    
    This enables clean regeneration and testing.
    
    Args:
        shacl_graph: The SHACL shapes graph
        node: The blank node to mark
    """
    shacl_graph.add((node, EX.generatedBy, Literal("ontology_entailer")))


def strip_generated_paths(shacl_graph: Graph) -> Graph:
    """
    Remove all generated property shapes from a shapes graph.
    
    Removes all blank nodes marked with ex:generatedBy "ontology_entailer".
    
    STATUS: Internal/testing utility only.
    
    NOTE: Copy-on-write is the mandatory approach for preprocessing.
    This function is provided for:
    - Debug/testing: inspect shapes before/after generation
    - Regression tests: strip generated nodes for comparison
    
    Not needed for normal operation since preprocessing always uses copy-on-write.
    
    Args:
        shacl_graph: The SHACL shapes graph
        
    Returns:
        Modified graph with generated nodes removed
    """
    result = Graph()
    result += shacl_graph
    
    # Find all generated nodes
    generated_nodes = set()
    for node, _, _ in result.triples((None, EX.generatedBy, Literal("ontology_entailer"))):
        generated_nodes.add(node)
    
    # Remove all triples involving generated nodes
    for node in generated_nodes:
        # Remove as subject
        for s, p, o in list(result.triples((node, None, None))):
            result.remove((s, p, o))
        # Remove as object
        for s, p, o in list(result.triples((None, None, node))):
            result.remove((s, p, o))
    
    logger.debug(f"Removed {len(generated_nodes)} generated property shapes")
    return result


def extract_allowed_paths(shacl_graph: Graph, shape: URIRef) -> Set[URIRef]:
    """
    Extract Allowed(shape) = Paths(shape) ∪ Ignored(shape).
    
    Returns:
        Set of all allowed property URIs for the shape
    
    Logic:
    1. Collect all sh:path values from sh:property nodes
    2. Collect all properties from sh:ignoredProperties RDF list
    3. Return union
    
    Args:
        shacl_graph: The SHACL shapes graph
        shape: Shape URI
        
    Returns:
        Set of all allowed property URIs
    """
    allowed = set()
    
    # 1. Collect all sh:path values from sh:property nodes
    for _, _, prop_node in shacl_graph.triples((shape, SH.property, None)):
        path = shacl_graph.value(prop_node, SH.path)
        if path and isinstance(path, URIRef):
            allowed.add(path)
    
    # 2. Collect all properties from sh:ignoredProperties RDF list
    ignored_list = shacl_graph.value(shape, SH.ignoredProperties)
    if ignored_list:
        ignored_props = get_elements_in_rdf_list(shacl_graph, ignored_list)
        allowed.update(p for p in ignored_props if isinstance(p, URIRef))
    
    return allowed


def entail_shape_from_ontology(
    ontology_graph: Graph,
    shacl_graph: Graph,
    shape_properties: Set[URIRef],
    property_shape: URIRef,
    shape: URIRef,
    regime: str,
    old_ignored_properties: Set[URIRef],
    subprop_closure: Dict[URIRef, Set[URIRef]]
) -> Tuple[Graph, Set[URIRef]]:
    """
    Extend shape with sub-properties from ontology closure.
    
    Args:
        ontology_graph: The ontology (not used if subprop_closure provided)
        shacl_graph: The SHACL shapes graph (modified in place)
        shape_properties: Current allowed property paths
        property_shape: Existing property shape blank node
        shape: Shape URI being extended
        regime: Inference regime (rdfs, owl-ld, owlrl)
        old_ignored_properties: Properties to skip
        subprop_closure: Precomputed closure from compute_subproperty_closure()
    
    Returns:
        Tuple of (modified shacl_graph, updated shape_properties set)
    
    Logic:
    1. Get property path `p` from property_shape
    2. Look up subprops[p] from closure
    3. For each q in subprops[p]:
         - If q not in shape_properties and q not in old_ignored_properties:
           - Create blank node with ONLY sh:path = q
           - Mark as generated (ex:generatedBy "ontology_entailer")
           - Add to shape
    """
    property_shape_path = shacl_graph.value(property_shape, SH.path)
    
    if not property_shape_path or not isinstance(property_shape_path, URIRef):
        return shacl_graph, shape_properties
    
    # Get sub-properties from precomputed closure
    subprops = subprop_closure.get(property_shape_path, set())
    
    # Sort for stable iteration order (deterministic output)
    for sub_prop in sorted(subprops, key=str):
        # Check if the new property is not already in the shape properties
        if sub_prop not in shape_properties and sub_prop not in old_ignored_properties:
            # Create a new property shape (path-only)
            property_node = BNode()
            shacl_graph.add((shape, SH.property, property_node))
            # Add ONLY the path
            shacl_graph.add((property_node, SH.path, sub_prop))
            # Mark as generated
            mark_generated_node(shacl_graph, property_node)
            
            shape_properties.add(sub_prop)
            logger.info(f"Added new property path {sub_prop} (sub-property of {property_shape_path})")
    
    return shacl_graph, shape_properties


def entail_has_value_from_ontology(
    ontology_graph: Graph,
    shape: URIRef,
    shacl_graph: Graph,
    shape_properties: Set[URIRef]
) -> Tuple[Graph, Set[URIRef]]:
    """
    Add property shapes based on OWL hasValue restrictions in ontology.
    
    Pattern matching (not full reasoning):
    - For each target class C (from sh:targetClass):
      - Find rdfs:subClassOf* _:b in ontology
      - If _:b has owl:onProperty ?p and owl:hasValue ?v:
        - Add property shape for ?p (path-only, marked as generated)
    
    Only active when regime = "owlrl"
    
    Args:
        ontology_graph: The ontology graph
        shape: The shape URI
        shacl_graph: The SHACL shapes graph
        shape_properties: Set of current property paths for the shape
        
    Returns:
        Tuple of (modified SHACL graph, updated property set)
    """
    target_classes = get_all_target_classes_for_shape(shape, shacl_graph)

    if not target_classes:
        return shacl_graph, shape_properties

    for target_class in target_classes:
        # Look in ontology for subClassOf restrictions
        for _, _, superclass_name in ontology_graph.triples((URIRef(target_class),
                                                             RDFS.subClassOf,
                                                             None)):

            on_property_value = ontology_graph.value(subject=superclass_name, predicate=OWL.onProperty)
            if on_property_value in shape_properties:
                continue

            bn_has_value_exists = ontology_graph.value(subject=superclass_name, predicate=OWL.hasValue) is not None
            bn_on_property_exists = on_property_value is not None

            if bn_has_value_exists and bn_on_property_exists:
                # Create path-only property shape
                property_node = BNode()
                shacl_graph.add((shape, SH.property, property_node))
                shacl_graph.add((property_node, SH.path, on_property_value))
                # Mark as generated
                mark_generated_node(shacl_graph, property_node)
                
                shape_properties.add(on_property_value)
                logger.info(f"Added new property path {on_property_value} (from hasValue restriction)")

    return shacl_graph, shape_properties


def extend_shacl_shape_from_ontology(
    shape: URIRef,
    property_blank_nodes: Set[BNode],
    shacl_graph: Graph,
    shape_properties: Set[URIRef],
    ontology_graph: Graph,
    regime: str,
    old_ignored_properties: Set[URIRef],
    subprop_closure: Dict[URIRef, Set[URIRef]]
) -> Graph:
    """
    Main orchestrator for shape extension using ontology.
    
    Replaces extend_shacl_shape() but uses ontology instead of data_graph.
    
    Logic:
    1. For each existing property shape:
         - Call entail_shape_from_ontology() with precomputed closure
    2. If regime == "owlrl":
         - Call entail_has_value_from_ontology()
    
    Args:
        shape: The shape URI
        property_blank_nodes: Set of existing property shape nodes
        shacl_graph: The SHACL shapes graph
        shape_properties: Set of current property paths
        ontology_graph: The ontology graph
        regime: The inference regime
        old_ignored_properties: Previously ignored properties
        subprop_closure: Precomputed closure from compute_subproperty_closure()
        
    Returns:
        The modified SHACL graph
    """
    # Extend based on subPropertyOf relationships
    for property_shape in property_blank_nodes:
        shacl_graph, shape_properties = entail_shape_from_ontology(
            ontology_graph, shacl_graph, shape_properties,
            property_shape, shape, regime, old_ignored_properties,
            subprop_closure
        )

    # Only in case of owlrl, add hasValue-based properties
    if regime == InferenceLevel.OWLRL.value:
        shacl_graph, shape_properties = entail_has_value_from_ontology(
            ontology_graph, shape, shacl_graph, shape_properties
        )

    return shacl_graph
